version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    entrypoint: wait-for db:3306 -t 40 -- sh ./entrypoint.sh
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
    - 8080:80
